### ISSUE TITLE
Breaks when the features is a single position

### ISSUE THREAD

**Issue by doomedramen** [udp/genbankjs#4]
example:

Misc._feature   2300..3089
                     /vntifkey="21"
                     /label="pUC ori"
                     /label="pUC ori"
IS GOOD

```
 Replication_ori 2335
                 /vntifkey="33"
                 /label=ORI
                 /note=" RNaseH cleavage point "
```

BREAKS

**Comment by doomedramen** [comment]
debug output:

```
 if (complement !== null) {
            location = complement[1];
          }
          console.log(location);
          location = location.replace(/[<>]/g, '').match(/^([0-9]+)\.\.([0-9]+)$/);
          console.log(location);
```

30..629
[ '30..629', '30', '629', index: 0, input: '30..629' ]
62..598
[ '62..598', '62', '598', index: 0, input: '62..598' ]
657..784
[ '657..784', '657', '784', index: 0, input: '657..784' ]
808..2289
[ '808..2289', '808', '2289', index: 0, input: '808..2289' ]
2300..3089
[ '2300..3089', '2300', '3089', index: 0, input: '2300..3089' ]
2335
null

**Comment by doomedramen** [comment]
not sure if a fix should be put before or after the `match`, probebly after, aka 

```
if(complement[1] && ! location) {
var location = [];
location[0] = complement[1];
location [1] = complement[1];
location [2] = complement[1];
}
```

then it will not fail here:

```
var f = {
            key: feature.name,
            location: {
              start: parseInt(location[1]),
              end: parseInt(location[2]),
              partial3Prime: partial3Prime,
              partial5Prime: partial5Prime,
              strand: complement !== null ? 'complementary' : 'forward'
            }
          };
```

**Comment by doomedramen** [comment]
ok, quick fix:

```
if (location.split('..').length < 2) {
            location = location + '..' + location;
          }
```

**Comment by jamesamcl** [comment]
Thanks, and apologies again for the late reply!

**Comment by doomedramen** [comment]
dont apologise, I assumed you were just sick of all my pulls requests and issue notifications :)

**Comment by jamesamcl** [comment]
Not at all - really appreciate your help!

I wrote this ages ago for another project and hadn't had another use for it until recently.  I'll make sure I'm on the ball with maintenance from now on.
