### ISSUE TITLE
does not handle joins

### ISSUE THREAD

**Issue by doomedramen** [udp/genbankjs#6]
Just as there is a check for compliments:

```
var complement = location.match(/^complement\((.+)\)$/);
```

there should be something to handle joins

I have tried:

```
 var join = location.match(/^join\((.+)\)$/);

          if (join !== null) {
            location = join[1];
          }
```

but I then have `852..1229,1419..1754` and I am not sure how to handle 2 sets of numbers...

**Comment by doomedramen** [comment]
I could just add two features instead of one but that does not seem like it would give a valid output for a join in the json

**Comment by doomedramen** [comment]
example of what is not handled:

LOCUS       pICSL50016      3154 bp    DNA     circular UNA 3-MAR-2009
COMMENT     This file is created by Vector NTI
            http://www.invitrogen.com/
FEATURES             Location/Qualifiers
     Misc._feature   1..615
                     /vntifkey="21"
                     /label="rep (pMB1)"
     Replication_ori complement(600)
                     /vntifkey="33"
                     /label=ORI
                     /note=" RNaseH cleavage point "
     Golden_Gate_Par 848..1758
                     /label=CT_turboGFPwithIntron
     CDS             join(852..1229,1419..1754) <-----HERE
                     /label="turbo GFP (Pontellina plumata)"
     Intron          1230..1418
                     /label="intron (U5 small nuclear ribonucleoprotein component (Arabidopsis thaliana))"
     CDS             1985..2995
                     /vntifkey="4"
                     /label="Sm/Sp no DraIII"
     Mutation        2962
                     /vntifkey="62"
                     /label="G to A"

**Comment by jamesamcl** [comment]
Hi, joins are implemented now.  Sorry for the late reply.
